### ISSUE TITLE
bug/vulnerability

### ISSUE THREAD

**Issue by kemoycampbell** [mikerockett/cpanelapi#1]
the function __call($name,$argument) unintentionally introduced an vulnerability that expose sensitive information of the class cpanelAPI including the password for the cpanel. This occurs as a result of the code in line 62 "return $this;". A working example of the vulnerability and exposure of sensivite data can be reproduce using print_r($cpanel->useUapi(true)->setScope('DomainInfo')->list_domains()). An easy fix is to remove the return $this; In additonal, the need for if empty argument block is unclear. I disable the block and it works as intended. Could you explain the need for if empty argument block?

**Comment by mikerockett** [comment]
The empty check is used for setting the API and scope. Thank you for identifying this; I'll be having a closer look at the package as I'd like to give it a refactor.

**Comment by mikerockett** [comment]
I'm actually going to deprecate this library - [the original by Toby](/N1ghteyes/cpanel-UAPI-php-class) has been improved from a usage standpoint, and this library really doesn't differ in functionality.
